
services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  fastapi_app:
    build: .
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "celery -A app.celery_worker.celery worker --loglevel=info & uvicorn app.main:app --host 0.0.0.0 --port 8000"

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"